services:
  # --- 1. Nginx: ประตูหน้าบ้าน (Reverse Proxy) ---
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"   # เปิดพอร์ต 80 ให้โลกภายนอกเข้าได้
    volumes:
      # ส่งไฟล์ config จากเครื่องเราเข้าไปใน Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - global-proxy-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
    # จำเป็นต้องแมปโวลุ่มพวกนี้ เพื่อให้ cAdvisor อ่านข้อมูลของ Docker ได้
    # / คือ root filesystem ของเครื่องโฮสต์
    # /var/run/docker.sock คือ เข้าไปหาไฟล์ docker.sock เพื่อคุยกับ Docker Engine ว่าตอนนี้มีคอนเทนเนอร์กี่ตัวที่รันอยู่
    # /sys คือ เข้าไปดูค่าการทำงานของ Kernel เช่น ตัวเลขการใช้งาน CPU และ RAM ที่แท้จริง
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - global-proxy-net
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - global-proxy-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # บรรทัดนี้สำคัญมาก ถ้าไม่มีจะเข้าผ่าน localhost ไม่ได้
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - global-proxy-net
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/  # บอก Grafana ว่า URL หลักคือที่นี่
      - GF_SERVER_SERVE_FROM_SUB_PATH=true            # ยืนยันการรันใน Sub-path
    networks:
      - global-proxy-net

networks:
  # บอก Docker ว่าไม่ต้องสร้างใหม่ ให้ไปใช้ "ถนนเส้นหลัก" ที่เราสร้างไว้แล้ว
  global-proxy-net:
    external: true